# Generated by Django 5.0 on 2024-04-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_roomimage_delete_roomphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
